name: WordPress Plugin PHPUnit Tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Plugin Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mysqli

      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install Composer Dependencies
        run: composer install || true

      - name: Setup WordPress Test Suite
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

      - name: Run PHPUnit
        run: |
          if [ -f ./vendor/bin/phpunit ]; then
            ./vendor/bin/phpunit
          else
            phpunit
          fi
